Mitrix/Areas/Admin/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mitrix.Areas.Admin.Models.ClientViewModels;
using Mitrix.Areas.Admin.Models.ContractTypeViewModels;
using Mitrix.Controllers;
using Mitrix.Data.Seeds;
using Mitrix.Infraestructure.Extensions;
using Mitrix.Infraestructure.Services.EmailSender;
using Mitrix.Models;
using Mitrix.Models.ApplicationUserViewModels;

namespace Mitrix.Areas.Admin.Controllers
{
    [Area(SeedRoles.ADMIN_ROLE)]
    [Authorize(Roles = SeedRoles.ADMIN_ROLE)]
    public class ClientController : AppController
    {
        private readonly IUserValidator<ApplicationUser> _userValidator;
        private readonly IEmailSender _emailSender;

        public ClientController(
            UserManager<ApplicationUser> userManager,
            IUserValidator<ApplicationUser> userValidator,
            IEmailSender emailSender) 
            : base(userManager)
        {
            _userValidator = userValidator;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Header = "List Clients";
            var model = await GetClients();
            return View(model);
        }

        public async Task<IActionResult> Details(string id)
        {
            var client = await GetClient(id);
            if (client != null)
            {
                ViewBag.Header = $"Client: {client.Name}";
                return View(client);
            }

            SetNotification("Client not found");
            return RedirectToAction(nameof(Index));
        }

        public ViewResult Create()
        {
            ViewBag.Header = "Create Client";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateClientViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var client = model.Create();
            var createClientIdentityResult = await UserManager.CreateAsync(client);
            if (!createClientIdentityResult.Succeeded)
            {
                AddErrorsFromResult(createClientIdentityResult);
                return View(model);
            }

            await UserManager.AddToRoleAsync(client, SeedRoles.CLIENT_ROLE);

            try
            {
                await PasswordResetLink(client, SetupPasswordType.NewClient, _emailSender);
                SetNotification("Client created");
            }
            catch (Exception)
            {
                SetNotification("Client Created but there was an error to save the email");  // warning
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(string id)
        {
            var client = await GetClient(id);
            if (client != null)
            {
                ViewBag.Header = $"Editing Client: {client.Name}";
                var model = EditClientViewModel.Create(client);
                return View(model);
            }

            SetNotification("Client not found");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditClientViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var client = await GetClient(model.Id);
            if (client != null)
            {
                model.UpdateClientFromModel(client);
                var identityResult = await _userValidator.ValidateAsync(UserManager, client);
                if (identityResult.Succeeded)
                {
                    identityResult = await UserManager.UpdateAsync(client);
                    if (identityResult.Succeeded)
                    {
                        SetNotification("Client Updated");
                        return RedirectToAction(nameof(Details), new { id = model.Id});
                    }
                }

                AddErrorsFromResult(identityResult);
                return View(model);
            }

            SetNotification("Client not found");
            return RedirectToAction(nameof(Index));
        }
    }
}

Mitrix/Areas/Admin/Controllers/ContractController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mitrix.Areas.Admin.Models.ClientViewModels;
using Mitrix.Areas.Admin.Models.ContractViewModels;
using Mitrix.Controllers;
using Mitrix.Data.Repositories;
using Mitrix.Data.Seeds;
using Mitrix.Infraestructure.ActionFilterAttributes;
using Mitrix.Infraestructure.Extensions;
using Mitrix.Models;

namespace Mitrix.Areas.Admin.Controllers
{
    [Area(SeedRoles.ADMIN_ROLE)]
    [Authorize(Roles = SeedRoles.ADMIN_ROLE)]
    public class ContractController : AppController
    {
        private readonly IRepository<ContractType> _contractTypeRepo;
        private readonly IRepository<Contract> _contractRepo;

        public ContractController(
            UserManager<ApplicationUser> userManager,
            IRepository<ContractType> contractTypeRepo,
            IRepository<Contract> contractRepo) 
            : base(userManager)
        {
            _contractTypeRepo = contractTypeRepo;
            _contractRepo = contractRepo;
        }

        public async Task<IActionResult> Index(string clientId)
        {
            var client = await GetClient(clientId);
            if (client != null)
            {
                ViewBag.Header = $"{client.Name} contracts";
                return View(client);
            }

            SetNotification("Client not found");
            return RedirectToAction(nameof(ClientController.Index), GetControllerName<ClientController>());
        }

        [HttpGet]
        public async Task<IActionResult> Create(string clientId)
        {
            var client = await GetClient(clientId);
            if (client != null)
            {
                ViewBag.Header = $"Create Contract for {client.Name}";
                var model = new CreateContractViewModel(GetSelectListContractTypes)
                {
                    ClientId = clientId
                };
                return View(model);
            }

            SetNotification("Client not found");
            return RedirectToAction(nameof(ClientController.Index), GetControllerName<ClientController>());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateContractViewModel model, string clientId)
        {
            var client = await GetClient(model.ClientId);
            if (client != null)
            {
                if (!ModelState.IsValid)
                {
                    return await Create(clientId);
                }

                var contract = model.GeContractFromModel();

                // todo: we must move this validation to a validation attrbute model
                if (Contract.SomeContractOverlappingDates(client.Contracts, contract.StartDate, contract.EndDate))
                {
                    ModelState.AddModelError(nameof(CreateContractViewModel.DateRange), "Overlapping another contracts");
                    return await Create(clientId);
                }

                _contractRepo.Create(contract);
                return RedirectToAction(nameof(Index), new { clientId = contract.ClientId });
            }

            SetNotification("Client not found");
            return RedirectToAction(nameof(ClientController.Index), GetControllerName<ClientController>());
        }

        public ActionResult Edit(string id)
        {
            var contract = _contractRepo.FetchAll()
                .AsQueryable()
                .Include(item => item.Client)
                .FirstOrDefault(item => item.Id == id);
            if (contract != null)
            {
                ViewBag.Header = $"Edit Contract for {contract.Client.Name}";
                return View(new EditContractViewModel(contract, contract.ClientId, new SelectList(
                    _contractTypeRepo.FetchAll().Where(item => item.Active),
                    nameof(ContractType.Id),
                    nameof(ContractType.Name))));
            }

            SetNotification("Contract not found");
            return RedirectToAction(
                actionName: nameof(ClientController.Index),
                controllerName: nameof(ClientController).Replace("Controller", ""));
        }

        [HttpPost]
        public ActionResult Edit(EditContractViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Edit(model.Id);
            }

            var contract = _contractRepo.FetchAll()
                .AsQueryable()
                .Include(item => item.Client)
                .FirstOrDefault(item => item.Id == model.Id);
            model.EditContractFromModel(contract);

            // todo: we must move this validation to a validation attrbute model
            if (Contract.SomeContractOverlappingDates(contract.Client.Contracts, contract.StartDate, contract.EndDate))
            {
                ModelState.AddModelError(nameof(CreateContractViewModel.DateRange), "Overlapping another contracts");
                return Edit(model.Id);
            }

            _contractRepo.Update(contract);
            return RedirectToAction(
                actionName: nameof(Index),
                controllerName: nameof(ContractController).Replace("Controller", ""),
                routeValues: new { clientId = contract.ClientId });
        }

        public async Task<IActionResult> All(ListAllContracts model)
        {
            model.ContractType = model.ContractType?.ToLower().Trim();
            var startDate = model.StartDate ?? DateTime.Now;
            var endDate = model.EndDate ?? DateTime.MaxValue;

            model.Contracts = (await GetClients())
                .SelectMany(item => item.Contracts)
                .Where(contract =>
                {
                    if (model.ContractType != null && !contract.ContractType.Name.Contains(model.ContractType))
                        return false;

                    return contract.StartDate.IsInRange(startDate, endDate)
                           || contract.EndDate.IsInRange(startDate, endDate);
                })
                .Select(contract => Tuple.Create(contract.Client, contract));

            ViewBag.Header = "List All Contracts";
            return View(model);
        }

        private SelectList GetSelectListContractTypes
        {
            get
            {
                return new SelectList(_contractTypeRepo.FetchAll()
                    .Where(item => item.Active), nameof(ContractType.Id), nameof(ContractType.Name));
            }
        }
    }
}

Mitrix/Areas/Admin/Controllers/ContractTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Mitrix.Areas.Admin.Models.ContractTypeViewModels;
using Mitrix.Controllers;
using Mitrix.Data.Repositories;
using Mitrix.Data.Seeds;
using Mitrix.Models;

namespace Mitrix.Areas.Admin.Controllers
{
    [Area(SeedRoles.ADMIN_ROLE)]
    [Authorize(Roles = SeedRoles.ADMIN_ROLE)]
    public class ContractTypeController : AppController
    {
        private readonly IRepository<ContractType> _contractTypeRepo;

        public ContractTypeController(
            UserManager<ApplicationUser> userManager,
            IRepository<ContractType> contractTypeRepo)
            : base(userManager)
        {
            _contractTypeRepo = contractTypeRepo;
        }

        public ViewResult Index()
        {
            ViewBag.Header = "List Contracts Types";
            return View(_contractTypeRepo.FetchAll());
        }

        public ViewResult Create()
        {
            ViewBag.Header = "Create Contract Type";
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateContractTypeViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var contractType = model.CreateContractTypeFromModel();
            _contractTypeRepo.Create(contractType);
            SetNotification("Contract Type created");
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(string id)
        {
            var contratType = _contractTypeRepo.Find(id);
            if (contratType == null)
            {
                SetNotification("Contract Type not found");
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Header = "Editing Contract Type";
            var model = new EditContractTypeViewModel(contratType);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditContractTypeViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var contractType = _contractTypeRepo.Find(model.Id);
            if (contractType == null)
            {
                SetNotification("Contract Type not found");
                return RedirectToAction(nameof(Index));
            }

            model.UpdateContractTypeFromModel(contractType);
            _contractTypeRepo.Update(contractType);
            SetNotification("Contract Type Updated");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            var contractType = _contractTypeRepo.Find(id);
            if (contractType != null)
            {
                _contractTypeRepo.Delete(contractType);
                SetNotification("Contract Type removed");
            }
            else
            {
                SetNotification("Contract Type not found");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Mitrix/Areas/Admin/Views/Shared/ClientContractsTabs.cshtml
@model String

<ul class="nav nav-tabs">
    <li asp-controller="Client" mit-active-route-actions="Details, Edit" mit-active-route-class="active">
        <a asp-controller="Client" asp-action="Details" asp-route-id="@Model">Client</a>
    </li>
    <li asp-controller="Contract" asp-action="Index" mit-active-route-class="active">
        <a asp-controller="Contract" asp-action="Index" asp-route-clientId="@Model" mit-active-route-class="active">Contracts</a>
    </li>
</ul>

Mitrix/Areas/Admin/Views/Shared/_AdminNavigation.cshtml
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /search-input -->
            </li>
            <li mit-active-route-controllers="Client,Contract" mit-active-route-actions="Index,Create,Edit,Details" mit-active-route-class="active">
                <a mit-active-route-controllers="Client,Contract" mit-active-route-actions="Edit,Details" mit-active-route-class="active">
                    <i class="fa fa-dashboard fa-fw"></i> Clients<span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a asp-controller="Client" asp-action="Index" mit-active-route-class="active"><i class="fa fa-bar-chart-o fa-fw"></i> Lists</a>
                    </li>
                    <li>
                        <a asp-controller="Client" asp-action="Create" mit-active-route-class="active"><i class="fa fa-table fa-fw"></i> Create</a>
                    </li>
                </ul>
            </li>
            <li asp-controller="Contract" asp-action="All" mit-active-route-class="active">
                <a asp-controller="Contract" asp-action="All" mit-active-route-class="active">
                    <i class="fa fa-files-o fa-fw"></i> Contracts
                </a>
            </li>
            <li asp-controller="ContractType" mit-active-route-actions="Index,Create,Edit,Details" mit-active-route-class="active">
                <a asp-controller="ContractType" mit-active-route-actions="Edit,Details" mit-active-route-class="active">
                    <i class="fa fa-edit fa-fw"></i> Nomenclatures<span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a asp-controller="ContractType" mit-active-route-actions="Edit,Details" mit-active-route-class="active">
                            <i class="fa fa-edit fa-fw"></i> Contracts Types<span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a asp-controller="ContractType" asp-action="Index" mit-active-route-class="active"><i class="fa fa-wrench fa-fw"></i> Lists</a>
                            </li>
                            <li>
                                <a asp-controller="ContractType" asp-action="Create" mit-active-route-class="active"><i class="fa fa-sitemap fa-fw"></i> Create</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i> Languages</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>