Mitrix/Areas/Client/Controllers/ClientObjectController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mitrix.Areas.Client.Models.ClientObjectViewModels;
using Mitrix.Controllers;
using Mitrix.Data.Repositories;
using Mitrix.Data.Seeds;
using Mitrix.Models;

namespace Mitrix.Areas.Client.Controllers
{
    [Area(SeedRoles.CLIENT_ROLE)]
    [Authorize(Roles = SeedRoles.CLIENT_ROLE)]
    public class ClientObjectController : AppController
    {
        private readonly IRepository<ClientObject> _clientObjectRepo;

        public ClientObjectController(
            UserManager<ApplicationUser> userManager,
            IRepository<ClientObject> clientObjectRepo) 
            : base(userManager)
        {
            _clientObjectRepo = clientObjectRepo;
        }

        public ViewResult Index()
        {
            ViewBag.Header = "List Client Objects";
            var currentUser = UserManager.Users
                .Include(item => item.ClientObjects)
                .FirstOrDefault(item => item.UserName == HttpContext.User.Identity.Name);
            return View(currentUser);
        }

        public ViewResult Create()
        {
            ViewBag.Header = "Create Client Object";
            return View(new CreateEditClientObjectViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEditClientObjectViewModel model)
        {
            if (!ModelState.IsValid)
                return View();

            var currentUser = await CurrentUser;
            var clientObject = model.GetNewClientObjectFromModel();
            clientObject.ClientId = currentUser.Id;
            _clientObjectRepo.Create(clientObject);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(string id)
        {
            var clientObject = _clientObjectRepo.Find(id);
            if (!await IsClientObjectOwner(clientObject))
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Header = $"Client Object {clientObject.Name} Details";
            return View(new CreateEditClientObjectViewModel(clientObject)
            {
                ReadOnly = true
            });
        }

        public async Task<IActionResult> Edit(string id)
        {
            var clientObject = _clientObjectRepo.Find(id);
            if (! await IsClientObjectOwner(clientObject))
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Header = $"Client Object {clientObject.Name} Details";
            return View(new CreateEditClientObjectViewModel(clientObject));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreateEditClientObjectViewModel model)
        {
            var clientObject = _clientObjectRepo.Find(model.Id);
            if (!await IsClientObjectOwner(clientObject))
            {
                return RedirectToAction(nameof(Index));
            }

            model.UpdateClientObjectFromModel(clientObject);
            _clientObjectRepo.Update(clientObject);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> IsClientObjectOwner(ClientObject clientObject)
        {
            if (clientObject == null)
            {
                SetNotification("Client Object Not Found");
                return false;
            }

            var currentUser = await CurrentUser;
            if (currentUser.Id != clientObject.ClientId)
            {
                SetNotification("You are not the Client Object owner");
                return false;
            }

            return true;
        }
    }
}

Mitrix/Areas/Client/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Mitrix.Areas.Client.Models.ProfileViewModels;
using Mitrix.Controllers;
using Mitrix.Data.Seeds;
using Mitrix.Models;
using Mitrix.Models.ApplicationUserViewModels;

namespace Mitrix.Areas.Client.Controllers
{
    [Area(SeedRoles.CLIENT_ROLE)]
    [Authorize(Roles = SeedRoles.CLIENT_ROLE)]
    public class ProfileController : AppController
    {
        private readonly IUserValidator<ApplicationUser> _userValidator;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IPasswordValidator<ApplicationUser> _passwordValidator;

        public ProfileController(
            UserManager<ApplicationUser> userManager,
            IUserValidator<ApplicationUser> userValidator, 
            SignInManager<ApplicationUser> signInManager, 
            IPasswordValidator<ApplicationUser> passwordValidator)
            : base(userManager)
        {
            _userValidator = userValidator;
            _signInManager = signInManager;
            _passwordValidator = passwordValidator;
        }

        public async Task<ActionResult> Index()
        {
            ViewBag.Header = "Profile Details";
            return View(await CurrentUser);
        }

        public async Task<ActionResult> Edit()
        {
            ViewBag.Header = "Edit Profile";
            var currentUser = await CurrentUser;
            var model = new EditProfileViewModel(currentUser);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditProfileViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var client = await CurrentUser;
            model.EditClientFromModel(client);

            client.Email = model.Email;
            var emailValidation = await _userValidator.ValidateAsync(UserManager, client);
            if (emailValidation.Succeeded)
            {
                await UserManager.UpdateAsync(client);
                SetNotification("Profile Updated");
                return RedirectToAction(nameof(Index));
            }

            AddErrorsFromResult(emailValidation);
            return View(model);
        }

        public IActionResult ChangePassword()
        {
            return View(new ChangePasswordViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var currentUser = await CurrentUser;
            var passwordValidation = await _passwordValidator.ValidateAsync(UserManager, currentUser, model.NewPassword);
            if (passwordValidation.Succeeded)
            {
                var changePasswordResult = await UserManager.ChangePasswordAsync(currentUser, model.CurrentPassword, model.NewPassword);
                if (changePasswordResult.Succeeded)
                {
                    SetNotification("Password updated");
                    await _signInManager.SignInAsync(currentUser, isPersistent: false);
                    return RedirectToAction(nameof(Index));
                }
                AddErrorsFromResult(changePasswordResult);
            }
            AddErrorsFromResult(passwordValidation);
            return View(model);
        }
    }
}

Mitrix/Areas/Client/Views/Shared/_ClientNavigation.cshtml
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /search-input -->
            </li>
            <li asp-controller="Profile" mit-active-route-actions="Index,Edit,ChangePassword" mit-active-route-class="active">
                <a asp-controller="Profile" mit-active-route-actions="" mit-active-route-class="active">
                    <i class="fa fa-dashboard fa-fw"></i> Profile<span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a asp-controller="Profile" asp-action="Index" mit-active-route-class="active"><i class="fa fa-bar-chart-o fa-fw"></i> Details</a>
                    </li>
                    <li>
                        <a asp-controller="Profile" asp-action="Edit" mit-active-route-class="active"><i class="fa fa-table fa-fw"></i> Edit</a>
                    </li>
                    <li>
                        <a asp-controller="Profile" asp-action="ChangePassword" mit-active-route-class="active"><i class="fa fa-table fa-fw"></i> Change Password</a>
                    </li>
                </ul>
            </li>
            <li asp-controller="ClientObject" mit-active-route-actions="Index,Create,Edit,Details" mit-active-route-class="active">
                <a asp-controller="ClientObject" mit-active-route-actions="Edit,Details" mit-active-route-class="active">
                    <i class="fa fa-edit fa-fw"></i> Client Objects<span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a asp-controller="ClientObject" asp-action="Index" mit-active-route-class="active">
                            <i class="fa fa-edit fa-fw"></i> List
                        </a>
                    </li>
                    <li>
                        <a asp-controller="ClientObject" asp-action="Create" mit-active-route-class="active">
                            <i class="fa fa-wrench fa-fw"></i> Create
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>