Mitrix/Models/ClientObject.cs
using System.ComponentModel.DataAnnotations;

namespace Mitrix.Models
{
    public class ClientObject
    {
        public string Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Url]
        public string WebAddress { get; set; }

        public string Description { get; set; }

        [Required]
        public string Country { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public double Lat { get; set; }

        [Required]
        public double Lng { get; set; }

        public bool Active { get; set; }

        [Required]
        public string ClientId { get; set; }
        public ApplicationUser Client { get; set; }
    }
}

Mitrix/Areas/Client/Controllers/ClientObjectController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mitrix.Areas.Client.Models.ClientObjectViewModels;
using Mitrix.Controllers;
using Mitrix.Data.Repositories;
using Mitrix.Data.Seeds;
using Mitrix.Models;

namespace Mitrix.Areas.Client.Controllers
{
    [Area(SeedRoles.CLIENT_ROLE)]
    [Authorize(Roles = SeedRoles.CLIENT_ROLE)]
    public class ClientObjectController : AppController
    {
        private readonly IRepository<ClientObject> _clientObjectRepo;

        public ClientObjectController(
            UserManager<ApplicationUser> userManager,
            IRepository<ClientObject> clientObjectRepo) 
            : base(userManager)
        {
            _clientObjectRepo = clientObjectRepo;
        }

        public ViewResult Index()
        {
            ViewBag.Header = "List Client Objects";
            var currentUser = UserManager.Users
                .Include(item => item.ClientObjects)
                .FirstOrDefault(item => item.UserName == HttpContext.User.Identity.Name);
            return View(currentUser);
        }

        public ViewResult Create()
        {
            ViewBag.Header = "Create Client Object";
            return View(new CreateEditClientObjectViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEditClientObjectViewModel model)
        {
            if (!ModelState.IsValid)
                return View();

            var currentUser = await CurrentUser;
            var clientObject = model.GetNewClientObjectFromModel();
            clientObject.ClientId = currentUser.Id;
            _clientObjectRepo.Create(clientObject);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(string id)
        {
            var clientObject = _clientObjectRepo.Find(id);
            if (!await IsClientObjectOwner(clientObject))
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Header = $"Client Object {clientObject.Name} Details";
            return View(new CreateEditClientObjectViewModel(clientObject)
            {
                ReadOnly = true
            });
        }

        public async Task<IActionResult> Edit(string id)
        {
            var clientObject = _clientObjectRepo.Find(id);
            if (! await IsClientObjectOwner(clientObject))
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Header = $"Client Object {clientObject.Name} Details";
            return View(new CreateEditClientObjectViewModel(clientObject));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreateEditClientObjectViewModel model)
        {
            var clientObject = _clientObjectRepo.Find(model.Id);
            if (!await IsClientObjectOwner(clientObject))
            {
                return RedirectToAction(nameof(Index));
            }

            model.UpdateClientObjectFromModel(clientObject);
            _clientObjectRepo.Update(clientObject);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> IsClientObjectOwner(ClientObject clientObject)
        {
            if (clientObject == null)
            {
                SetNotification("Client Object Not Found");
                return false;
            }

            var currentUser = await CurrentUser;
            if (currentUser.Id != clientObject.ClientId)
            {
                SetNotification("You are not the Client Object owner");
                return false;
            }

            return true;
        }
    }
}

Mitrix/Components/GeoLocationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mitrix.Models.ComponentsViewModels;

namespace Mitrix.Components
{
    public class GeoLocationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(GeoLocationViewModel model)
        {
            return View(model);
        }
    }
}

Mitrix/Areas/Client/Views/ClientObject/Create.cshtml
@model CreateEditClientObjectViewModel

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" method="post">
    
    @Html.EditorForModel()

    <button type="submit" class="btn btn-primary">Create</button>
    <a asp-action="Index" class="btn btn-default">Cancel</a>
</form>

@section styles{
    @{ await Html.RenderPartialAsync("StylesGeoLocation"); }
}

@section scripts{
    @{ await Html.RenderPartialAsync("ScriptsGeoLocation"); }
}

Mitrix/Areas/Client/Views/ClientObject/Details.cshtml
@model CreateEditClientObjectViewModel

<div class="row">
    <div class="col-xs-6">
        <div class="form-group">
            <label asp-for="Name"></label>
            <p class="form-control-static">@Model.Name</p>
        </div>

        <div class="form-group">
            <label asp-for="WebAddress"></label>
            <p class="form-control-static">@Model.Name</p>
        </div>

        <div class="form-group">
            <label asp-for="Description"></label>
            <p class="form-control-static">@Model.Name</p>
        </div>

        <div class="form-group">
            <label asp-for="Country"></label>
            <p class="form-control-static">@Model.Country</p>
        </div>

        <div class="form-group">
            <label asp-for="Active"></label>
            <p class="form-control-static">@Model.Active</p>
        </div>
    </div>

    <div class="col-xs-6">
        @await Component.InvokeAsync("GeoLocation", Model.GeoLocationViewModel)
    </div>
    
    <div class="col-xs-12">
        <a class="btn btn-default" asp-action="Index">List</a>
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</div>

@section styles{
    @{ await Html.RenderPartialAsync("StylesGeoLocation"); }
}

@section scripts{
    @{ await Html.RenderPartialAsync("ScriptsGeoLocation"); }
}

Mitrix/Areas/Client/Views/ClientObject/Edit.cshtml
@model CreateEditClientObjectViewModel

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Edit" method="post">

    @Html.EditorForModel()

    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-default">Cancel</a>
</form>

@section styles{
    @{ await Html.RenderPartialAsync("StylesGeoLocation"); }
}

@section scripts{
    @{ await Html.RenderPartialAsync("ScriptsGeoLocation"); }
}

Mitrix/Areas/Client/Views/ClientObject/Index.cshtml
@model ApplicationUser

<table class="display datatable table table-condensed table-bordered table table-striped table-hover" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Country</th>
            <th>Address</th>
            <th>Description</th>
            <th>Active</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ClientObjects)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Country</td>
                <td>@item.Address</td>
                <td>@item.Description</td>
                <td class="text-center"><i mit-status="@item.Active"></i></td>
                <td>
                    <a class="btn btn-primary btn-sm" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    <a class="btn btn-primary btn-sm" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-action="Create">Create</a>